name: Go

on:
  push:
   branches-ignore: 
    - "release/v*.*.*eden*.*.*"
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test ./core ./miner/... ./internal/ethapi/... ./les/...

    - name: Build
      run: make geth